[settings]
experimental = true
lockfile = true

[tools]
# https://developer.rebble.io/sdk/
# https://github.com/coredevices/pebble-tool
# https://mise.jdx.dev/dev-tools/backends/pipx.html
"pipx:pebble-tool" = "5.0.38"

[env]
_.file = ".env"

[tasks.clean]
description = "Clean build artifacts"
run = "pebble clean"

[tasks.build]
description = "Build PBW"
run = "scripts/build.sh"

[tasks.rebuild]
description = "Clean and rebuild PBW"
run = "pebble clean && scripts/build.sh"

[tasks.install-phone]
description = "Build and install on phone"
alias = "install"
run = "scripts/install-phone.sh"

[tasks.install-cloud]
description = "Build and install on CloudPebble"
alias = "cloud"
run = "scripts/install-cloud.sh"

[tasks.install-emulator]
description = "Build and install on emulator (default emulator: basalt)"
alias = "emu"
run = "pebble wipe && scripts/install-emulator.sh"

[tasks.kill-emulator]
description = "Stop running emulator and phone simulator"
alias = "kill"
run = "pebble kill"
